### ISSUE TITLE
Handle null/infinity/NaN

### ISSUE THREAD

**Issue by thambaru** [innovuslk/pms_fe#41]
1.
![Screenshot from 2024-09-25 10-04-45](https://github.com/user-attachments/assets/e817391e-6fc2-45ba-95a5-9fbe355b8e00)

2.
![Screenshot from 2024-09-25 10-03-01](https://github.com/user-attachments/assets/9f4d9268-5834-47a0-8d6b-08ed21986ed0)

3.
![Screenshot from 2024-09-25 09-59-32](https://github.com/user-attachments/assets/22f6e321-e2b8-4c27-b0d9-a846eb86f941)

**Comment by Mahith-Innovus** [comment]
Done
